<?
$sezione = 2;

$nomeprogetto['it'] = "Letteratura visiva";
$nomeprogetto['en'] = "Visual literature";

include ("andrea-header.php"); ?>

  <!-- Page Title -->
  <section class="page-title page-title-banner page-title-image-parallax space-bottom-3x" style="background-image:url(img/portfolio/vislit/vislit-header.png);">
    <div class="container">
      <h1><?=$nomeprogetto[$lingua]?></h1>
      <!-- <ol class="breadcrumb">
        <li><a href="index.html"><?=$titolo[$lingua][0]?></a></li>
        <li><a href="<?=$menu_link[$lingua][$sezione]?>"><?=$titolo[$lingua][$sezione]?></a></li>
        <li><?=$nomeprogetto[$lingua]?></li>
      </ol> -->
    </div>
  </section>

  <!-- Project Overview -->
  <section class="container space-bottom-2x">
    <div class="block-title">
      <h2>Project Overview</h2>
      <hr class="hr-bold hr-info">
    </div>
    <div class="row">
      <div class="col-md-7 col-sm-6">
        <div class="row">
          <div class="col-md-8">
            <h5 class="text-info space-bottom">Overview</h5>
            <p>The project tries to visualize the writing style of an author through a diagram generated by the rhythm of the text.<br>While the text is read from left to right, the diagram grows from bottom to top: a complex and articulated writing flow will produce a high and wide shape, while a blunt and concise prose will result in a smaller and sharper diagram.</p>
          </div>
          <div class="col-md-4">
            <h5 class="text-info space-bottom">Tools</h5>
            <ul class="list-unordered">
              <li>Processing<br>(static prototype)</li>
              <li>D3 + Javascript<br>(interactive visualization)</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-5 col-sm-6">
        <div class="row">
          <div class="col-md-5">
            <h5 class="text-info space-bottom">Tasks</h5>
            <ul class="list-unordered">
              <li>Concept</li>
              <li>Data collection</li>
              <li>Data processing</li>
              <li>Visual Design</li>
              <li>Prototyping</li>
              <li>Front-End Coding</li>
            </ul>
          </div>
          <div class="col-md-7">
            <h5 class="text-info space-bottom">Client</h5>
            <span class="space-bottom inline">Self-initiated</span><br>
            <a href="http://www.andreacorradi.com/visual_literature/" target="_blank" class="btn btn-primary">Visit website</a>
          </div>
        </div>
      </div>
    </div>
    <div class="space-top-2x visible-xs"></div>
    <div class="single-post-meta space-top">
      <!-- <div class="column">
        <div class="post-meta">
          <span>March 30, 2015 Developed in collaboration with...</span>
        </div>
      </div> -->
    </div>
    <hr>
    <!-- <div class="tags">
      <a href="#" class="tag tag-info">Web Design</a>
      <a href="#" class="tag tag-success">Development</a>
      <a href="#" class="tag tag-warning">Company Identity</a>
    </div> -->
  </section><!-- Project Overview End -->


  <!-- Single image -->
  <section class="section-fw">
    <div class="container-singlework-grid">
      <img src="img/portfolio/vislit/vislit-tile-col1-1v2.png" class="block-center" alt="">
    </div>
  </section>
  <!-- Single image -->


  <!-- Text -->
  <section class="container padding-bottom-2x">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <blockquote>
          <p>Each sentence is represented by a line: the longer the sentence, the longer the line. If there are no comas (, ; :) the line will be vertical; comas produce a drift from the central axes. Red and green represent respectively sentences ending with question and exclamation marks.</p>
          <!-- <footer>C.E.R.A. Rapone</footer> -->
        </blockquote>
      </div>
    </div>
  </section>


  <!-- Double image -->
  <section class="section-split bg-solid-white">
    <div class="column-singlework-grid2">
      <img data-src="img/portfolio/vislit/proust.png" class="lazyload" alt=""><noscript><img src="img/portfolio/vislit/proust.png" /></noscript>
    </div>
    <div class="column-singlework-grid2">
      <img data-src="img/portfolio/vislit/london.png" class="lazyload" alt=""><noscript><img src="img/portfolio/vislit/london.png" /></noscript>
    </div>
  </section><!-- Double image -->


  <!-- Double image -->
  <section class="section-split bg-solid-white">
    <div class="column-singlework-grid2">
      <img data-src="img/portfolio/vislit/dickens.png" class="lazyload" alt=""><noscript><img src="img/portfolio/vislit/dickens.png" /></noscript>
    </div>
    <div class="column-singlework-grid2">
      <img data-src="img/portfolio/vislit/joyce.png" class="lazyload" alt=""><noscript><img src="img/portfolio/vislit/joyce.png" /></noscript>
    </div>
  </section><!-- Double image -->


  <!-- Text -->
  <section class="container space-top-3x padding-bottom-2x">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <blockquote>
          <p>Each paragraph includes one to many sentences; it sprouts from a single point at the very bottom and grow up. The whole text is represented by the overlay of all the paragraphs.</p>
          <!-- <footer>C.E.R.A. Rapone</footer> -->
        </blockquote>
      </div>
    </div>
  </section>


  <!-- Container -->
  <section class="container padding-top-2x padding-bottom-2x">

    <div class="block-title">
      <h2>Project Explanation</h2>
      <hr class="hr-bold hr-info">
    </div>

    <!-- Content slider -->
    <!-- To make dots light color (for darker images) apply ".text-light" class to any parent element. -->
    <!-- Add ".controls-inside" class to position next / prev arrows inside carousel. -->
    <!-- Data API: data-loop="true/false"; data-autoplay="true/false"; data-interval="3000" (in miliseconds); data-autoheight="true/false" (height adjustment to the content). -->
    <div class="content-slider controls-inside text-light" data-loop="true">
      <div class="item">
        <img data-src="img/portfolio/vislit/vislit-expl2.png" class="lazyload" alt="Image"><noscript><img src="img/portfolio/vislit/vislit-expl2.png" /></noscript>
      </div>
      <div class="item">
        <img data-src="img/portfolio/vislit/vislit-expl3.png" class="lazyload" alt="Image"><noscript><img src="img/portfolio/vislit/vislit-expl3.png" /></noscript>
      </div>
      <div class="item">
        <img data-src="img/portfolio/vislit/vislit-expl4.png" class="lazyload" alt="Image"><noscript><img src="img/portfolio/vislit/vislit-expl4.png" /></noscript>
      </div>
      <div class="item">
        <img data-src="img/portfolio/vislit/vislit-expl5.png" class="lazyload" alt="Image"><noscript><img src="img/portfolio/vislit/vislit-expl5.png" /></noscript>
      </div>
      <div class="item">
        <img data-src="img/portfolio/vislit/vislit-expl6.png" class="lazyload" alt="Image"><noscript><img src="img/portfolio/vislit/vislit-expl6.png" /></noscript>
      </div>
      <div class="item">
        <img data-src="img/portfolio/vislit/vislit-expl7.png" class="lazyload" alt="Image"><noscript><img src="img/portfolio/vislit/vislit-expl7.png" /></noscript>
      </div>
      <div class="item">
        <img data-src="img/portfolio/vislit/vislit-expl8.png" class="lazyload" alt="Image"><noscript><img src="img/portfolio/vislit/vislit-expl8.png" /></noscript>
      </div>
      <div class="item">
        <img data-src="img/portfolio/vislit/vislit-expl9.png" class="lazyload" alt="Image"><noscript><img src="img/portfolio/vislit/vislit-expl9.png" /></noscript>
      </div>
    </div>

  </section><!-- Container End -->


  <!-- Text -->
  <section class="container space-top-3x padding-bottom-2x">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <blockquote>
          <p>During the project development I worked out also a static version —made with Processing— which uses the letters of the text to build the tree branches. This is conceptually more fascinating even if it's not suited for small size interactive media. It could be very interesting to print it in large size.</p>
          <!-- <footer>C.E.R.A. Rapone</footer> -->
        </blockquote>
      </div>
    </div>
  </section>


  <!-- Single image -->
  <section class="section-fw">
    <div class="container-singlework-grid">
      <img data-src="img/portfolio/vislit/letters.jpg" class="block-center lazyload" alt=""><noscript><img src="img/portfolio/vislit/letters.jpg" class="block-center" /></noscript>
    </div>
  </section>
  <!-- Single image -->


  <!-- Scroll to Top Button -->
  <!-- Use 'data-scroll-top' attribute to set value at which point the scroll to top button appears. -->
  <a href="#" class="btn btn-icon btn-primary scroll-to-top-btn scroll-up" data-scroll-top="600">
    <i class="pe-7s-angle-up"></i>
  </a>

  <? include ("andrea-footer.php"); ?>


  <!-- JavaScript (jQuery) libraries and scripts -->
  <script src="js/libs/jquery-1.11.2.min.js"></script>
  <script src="js/libs/jquery.easing.min.js"></script>
  <script src="js/plugins/bootstrap.min.js"></script>
  <script src="js/plugins/smoothscroll.js"></script>
  <script src="js/plugins/velocity.min.js"></script>
  <script src="js/plugins/form-plugins.js"></script>
  <script src="js/plugins/waypoints.min.js"></script>
  <script src="js/plugins/icon-click-effect.js"></script>

  <script src="masterslider/masterslider.min.js"></script>

  <script src="js/plugins/owl.carousel.min.js"></script>
  <script src="js/plugins/jquery.magnific-popup.min.js"></script>
  <script src="js/plugins/morph-devices.js"></script>
  <script src="js/scripts.js"></script>
  <script src="js/md-init.js"></script>

</body><!-- Body End -->

</html>
